[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cwd = "."
cmd = "npm install"

[phases.build]
cmd = "npm run build"
cwd = "."

[start]
cmd = "npm start"
cwd = "."